apiVersion: v1
kind: Service
metadata:
  name: demo-app-ui
spec:
  selector:
    app: demo-app-ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
    - name: https
      port: 443
      targetPort: 3000
